table fGols
	lineageTag: 70590f63-8ecf-45d7-bb43-4b950428b18d

	column PartidaId
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d2c586de-7052-4706-bf56-ce3e0297b85d
		summarizeBy: none
		sourceColumn: PartidaId

	column Clube
		dataType: string
		isHidden
		lineageTag: a3f1b9a7-d689-4aef-97ea-fb5572500af2
		summarizeBy: none
		sourceColumn: Clube

	column Atleta
		dataType: string
		isHidden
		lineageTag: 69bdecdb-135b-44c0-ac8b-5c047db67dde
		summarizeBy: none
		sourceColumn: Atleta

	column Minuto
		dataType: int64
		formatString: 0
		lineageTag: 886f3c52-62ab-43f4-a160-04dbd4f03965
		summarizeBy: none
		sourceColumn: Minuto

	column TipoGol
		dataType: string
		lineageTag: 3217677b-8582-4d76-ac76-10d4aab7656a
		summarizeBy: none
		sourceColumn: TipoGol

	column MinutoTexto
		dataType: string
		lineageTag: e081233b-b934-4e8e-b1e7-6fe58c85d943
		summarizeBy: none
		sourceColumn: MinutoTexto

	column Acrescimo
		dataType: int64
		formatString: 0
		lineageTag: 873f46ef-1ffe-4419-b685-1a2229b567de
		summarizeBy: none
		sourceColumn: Acrescimo

	column Data
		dataType: dateTime
		isHidden
		formatString: dd/MM/yyyy
		lineageTag: 9e31b0d8-dd72-475a-b45c-1b03fb4fdcb3
		summarizeBy: none
		sourceColumn: Data

		annotation UnderlyingDateTimeDataType = Date

	column FaixaMinuto
		dataType: string
		lineageTag: 1a4b4f1d-9f15-401a-be58-1cbf2c9a9ae7
		summarizeBy: none
		sourceColumn: FaixaMinuto
		sortByColumn: FaixaMinutoOrdem

	column FaixaMinutoOrdem
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 7c58aa95-8f7c-4881-8c59-0705c800d1d3
		summarizeBy: none
		sourceColumn: FaixaMinutoOrdem

	column GolAtleta
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: dfce1667-f11c-4e9e-abe1-da47e32398ee
		summarizeBy: sum
		sourceColumn: GolAtleta

	partition fGols = m
		mode: import
		queryGroup: Fatos
		source =
				let
				    Fonte = fxLerCsv("campeonato-brasileiro-gols.csv"),
				    ColunasRenomeadas = Table.RenameColumns(Fonte, {
				        {"partida_id", "PartidaId"}, {"clube", "Clube"},
				        {"atleta", "Atleta"}, {"minuto", "MinutoTexto"}, {"tipo_de_gol", "TipoGol"}
				    }),
				    // Rodada já está em dPartida
				    RodadaRemovida = Table.RemoveColumns(ColunasRenomeadas, {"rodata"}),
				    VaziosComoNulo = Table.ReplaceValue(RodadaRemovida, "", null, Replacer.ReplaceValue, {"Atleta"}),
				    // Tipo vazio = gol comum (só Penalty e Gol Contra vêm preenchidos)
				    TipoGolPadronizado = Table.ReplaceValue(VaziosComoNulo, "", "Normal", Replacer.ReplaceValue, {"TipoGol"}),
				    TiposDefinidos = Table.TransformColumnTypes(TipoGolPadronizado, {
				        {"PartidaId", Int64.Type}, {"Clube", type text},
				        {"Atleta", type text}, {"MinutoTexto", type text}, {"TipoGol", type text}
				    }, "pt-BR"),
				    // "45+2" = minuto 45 com 2 de acréscimo; separado para permitir faixa de minuto e ordenação
				    MinutoAdicionado = Table.AddColumn(TiposDefinidos, "Minuto",
				        each Number.From(Text.Split([MinutoTexto], "+"){0}), Int64.Type),
				    AcrescimoAdicionado = Table.AddColumn(MinutoAdicionado, "Acrescimo",
				        each Number.From(Text.Split([MinutoTexto], "+"){1}? ?? "0"), Int64.Type),
				    // Data da partida para ligar o fato direto ao calendário
				    // Faixas de 15'; os acréscimos de cada tempo têm faixa própria (45+ e 90+)
				    FaixaOrdemAdicionada = Table.AddColumn(AcrescimoAdicionado, "FaixaMinutoOrdem",
				        each fxFaixaMinuto([Minuto], [Acrescimo]), Int64.Type),
				    FaixaAdicionada = Table.AddColumn(FaixaOrdemAdicionada, "FaixaMinuto",
				        each {"0–15", "16–30", "31–45", "45+", "46–60", "61–75", "76–90", "90+"}{[FaixaMinutoOrdem] - 1},
				        type text),
				    // 1 = gol que conta na artilharia do autor (gol contra não conta); permite Top N por soma de coluna
				    GolAtletaAdicionado = Table.AddColumn(FaixaAdicionada, "GolAtleta",
				        each if [TipoGol] = "Gol Contra" then 0 else 1, Int64.Type),
				    PartidaMesclada = Table.NestedJoin(GolAtletaAdicionado, {"PartidaId"},
				        stgPartidas, {"PartidaId"}, "Partida", JoinKind.LeftOuter),
				    DataExpandida = Table.ExpandTableColumn(PartidaMesclada, "Partida", {"Data"}),
				    DataTipada = Table.TransformColumnTypes(DataExpandida, {{"Data", type date}})
				in
				    DataTipada

